"""Prepare a small, source-linked LDR reflection hypothesis; never edit a master.

The existing candidate CV-to-served rotation is baked into a Three.js equirect
derivative. It is NOT a newly accepted registration or calibrated HDR lighting.
"""
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_uv(served_rays, rotation):
    cv = served_rays @ rotation  # inverse rotation for row vectors
    return (np.arctan2(cv[..., 0], cv[..., 2]) / (2 * np.pi)) % 1, np.arccos(np.clip(-cv[..., 1], -1, 1)) / np.pi


def prepare(source, probe_path, output, receipt):
    if source.resolve() in (output.resolve(), receipt.resolve()):
        raise ValueError("Output must not overwrite the source")
    probe_text = probe_path.read_text(encoding="utf-8")
    probe = json.loads(probe_text[probe_text.index("{"):probe_text.rindex("}") + 1])
    before = sha(source)
    if before != probe["source_sha256"]:
        raise ValueError("Panorama does not match the recorded lighting source")
    rotation = np.array(probe["candidate_served_from_panorama_rotation"])
    if not np.allclose(rotation.T @ rotation, np.eye(3), atol=1e-6) or not np.isclose(np.linalg.det(rotation), 1):
        raise ValueError("Expected a proper rotation")
    with Image.open(source) as image:
        native_size = image.size
        rgb = np.asarray(image.convert("RGB").resize((1024, 512), Image.Resampling.BOX), dtype=float)
    width, height = 1024, 512
    u, v = np.meshgrid((np.arange(width) + .5) / width, (np.arange(height) + .5) / height)
    lon, lat = (u - .5) * 2 * np.pi, (.5 - v) * np.pi
    served = np.stack([np.cos(lat) * np.cos(lon), np.sin(lat), np.cos(lat) * np.sin(lon)], axis=-1)
    su, sv = source_uv(served, rotation)
    x, y = su * width - .5, np.clip(sv * height - .5, 0, height - 1)
    x0, y0 = np.floor(x).astype(int), np.floor(y).astype(int)
    tx, ty = (x - x0)[..., None], (y - y0)[..., None]
    top = rgb[y0, x0 % width] * (1 - tx) + rgb[y0, (x0 + 1) % width] * tx
    bottom = rgb[np.minimum(y0 + 1, height - 1), x0 % width] * (1 - tx) + rgb[np.minimum(y0 + 1, height - 1), (x0 + 1) % width] * tx
    derivative = np.rint(top * (1 - ty) + bottom * ty).clip(0, 255).astype(np.uint8)
    output.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(derivative).save(output, quality=92, subsampling=0, optimize=True)
    if sha(source) != before:
        raise ValueError("Source changed during preparation")
    result = {
        "schema": "venviewer.furniture-reflection-hypothesis.v1",
        "authority": "presentation-experiment-only", "accepted_registration": False,
        "radiometrically_calibrated": False, "source": source.name,
        "source_sha256": before, "source_bytes": source.stat().st_size,
        "native_size": list(native_size), "derivative": output.name,
        "derivative_sha256": sha(output), "derivative_bytes": output.stat().st_size,
        "derivative_size": [width, height],
        "candidate_served_from_panorama_rotation": rotation.tolist(),
        "orientation": "Candidate rotation baked into pixels: Three r180 equirectUv atan(z,x)/(2pi)+0.5; image top is +Y. Scene environmentRotation is identity.",
        "processing": "RGB BOX downsample, inverse candidate rotation, wrapped bilinear resample, JPEG quality92 4:4:4. No exposure gain, inpainting or invented highlights.",
        "limitations": "8-bit tone-mapped JPEG, assumed sRGB; capture-time lighting and provisional azimuth. Native polar content retained. Not HDR, measured BRDF, accepted registration or current illumination.",
    }
    receipt.parent.mkdir(parents=True, exist_ok=True)
    receipt.write_text("// Generated by tools/furniture-lighting/prepare_reflection_panorama.py.\nexport const GRAND_HALL_FURNITURE_REFLECTION_SOURCE = " + json.dumps(result, indent=2) + " as const;\n", encoding="utf-8")
    print(json.dumps(result))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("probe", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("receipt", type=Path)
    args = parser.parse_args()
    prepare(args.source, args.probe, args.output, args.receipt)
