// Generated by tools/furniture-lighting/measure_panorama.py.
// Source-linked presentation hypothesis, not calibrated illumination.
export const GRAND_HALL_FURNITURE_LIGHTING_PROBE = {
  "schema": "venviewer.furniture-lighting-hypothesis.v1",
  "source": "sweep_041jpg.jpg",
  "source_sha256": "d9d056e2453a223144514bdca224bbdfb7e76f4bd7130008a3d811afa67eb974",
  "native_size": [
    8192,
    4096
  ],
  "analysis_size": [
    1024,
    512
  ],
  "authority": "presentation-experiment-only",
  "accepted_registration": false,
  "radiometrically_calibrated": false,
  "source_view": "blue evening window sky; illuminated chandeliers and ceiling wash",
  "excluded_polar_rows_fraction": [
    0.056640625,
    0.13671875
  ],
  "represented_solid_angle_fraction": 0.9466890377387257,
  "rig_report_sha256": "e6c175d227fc49864a237f6cee46f6eb9781bc1dfff454534ca9fee7bf983c63",
  "mesh_fit_report_sha256": "3e34c54b7070db97254260e5ad1dbecf8c52956b66b2d38a990d584cb09afcef",
  "bearing_convention": "u,v are normalized pixel centres; lon=2pi*u, lat=pi/2-pi*v; panorama CV ray=[cos(lat)*sin(lon),-sin(lat),cos(lat)*cos(lon)]",
  "transform_composition": "served_from_panorama = target_zup_to_served_yup * candidate_target_from_e57 * candidate_e57_from_panorama; directions use rotation only, no translation",
  "target_zup_to_served_yup_rotation": [
    [
      1.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.0,
      1.0
    ],
    [
      0.0,
      -1.0,
      0.0
    ]
  ],
  "candidate_target_from_e57_rotation": [
    [
      0.021716130389303128,
      0.9997635367053785,
      -0.0011315278470772525
    ],
    [
      -0.9997551953573751,
      0.02172071885030779,
      0.004214229296464273
    ],
    [
      0.004237810384158196,
      0.0010397340909145888,
      0.9999904799127682
    ]
  ],
  "candidate_e57_from_panorama_rotation": [
    [
      -0.8282988034005617,
      0.0027629911009708916,
      -0.5602798034601758
    ],
    [
      0.5602142455474434,
      -0.01198793336761616,
      -0.8282610026672043
    ],
    [
      -0.009005074730752436,
      -0.9999243248035075,
      0.008381723888557562
    ]
  ],
  "candidate_served_from_e57_rotation": [
    [
      0.021716130389303128,
      0.9997635367053785,
      -0.0011315278470772525
    ],
    [
      0.004237810384158196,
      0.0010397340909145888,
      0.9999904799127682
    ],
    [
      0.9997551953573751,
      -0.02172071885030779,
      -0.004214229296464273
    ]
  ],
  "candidate_served_from_panorama_rotation": [
    [
      0.5421045201181198,
      -0.010793654967898096,
      -0.8402417427621278
    ],
    [
      -0.011932688422580507,
      -0.9999155606673331,
      0.005146113324029152
    ],
    [
      -0.8402263386817347,
      0.007236611622030255,
      -0.5421875424958774
    ]
  ],
  "upper_excess_threshold_linear": 0.4068757547480956,
  "source_exposure_gain": 2.1506974765348366,
  "diffuse_sh_rgb": [
    [
      1.5793081718821718,
      1.2171802677707226,
      0.982376425610935
    ],
    [
      0.06620141424276674,
      0.09152920819585698,
      0.1523729933105081
    ],
    [
      0.3260497963173912,
      0.32956576651569086,
      0.290026709324835
    ],
    [
      0.32999343120403873,
      0.21564889885893535,
      0.05918043734936545
    ],
    [
      -0.24673442682957397,
      -0.23187941773878104,
      -0.2802101204204092
    ],
    [
      -0.2891587598630125,
      -0.2811669127862732,
      -0.2579656653198829
    ],
    [
      -0.04014282190097032,
      -0.057586711910918124,
      -0.07022723785207997
    ],
    [
      0.19537130047854628,
      0.21830861852425357,
      0.20882983659154422
    ],
    [
      -0.008069743013402592,
      0.03963331195147551,
      0.11278567268696137
    ]
  ],
  "key_direction_to_light": [
    0.21953984602644444,
    0.9756020913201101,
    -0.0016779208898974024
  ],
  "key_linear_rgb_irradiance": [
    0.18530377894091468,
    0.12584727683425714,
    0.10413801755176534
  ],
  "upward_reference_luminance": 1.3567852958311728,
  "upward_candidate_luminance": 1.3567852958311728,
  "sampled_min_residual_irradiance": 0.396827084115028,
  "regions": {
    "window_blue_sky": {
      "uv_rectangle": [
        0.886,
        0.187,
        0.955,
        0.37
      ],
      "mean_linear_luminance": 0.07383234837779235,
      "p95_linear_luminance": 0.24358174061256468,
      "candidate_served_direction": [
        -0.7703495657810496,
        0.6346634994550339,
        -0.06134972665333437
      ]
    },
    "near_chandelier": {
      "uv_rectangle": [
        0.502,
        0.21,
        0.583,
        0.326
      ],
      "mean_linear_luminance": 0.25973992584671274,
      "p95_linear_luminance": 0.6648884873616148,
      "candidate_served_direction": [
        0.507775575242982,
        0.6600078566583967,
        0.5536728224645383
      ]
    },
    "ceiling_paint": {
      "uv_rectangle": [
        0.403,
        0.145,
        0.474,
        0.269
      ],
      "mean_linear_luminance": 0.17897750904605061,
      "p95_linear_luminance": 0.25876715231266306,
      "candidate_served_direction": [
        0.6136181695667227,
        0.7821161626573165,
        0.10847603462414465
      ]
    },
    "floor": {
      "uv_rectangle": [
        0.387,
        0.619,
        0.661,
        0.787
      ],
      "mean_linear_luminance": 0.39680873612406253,
      "p95_linear_luminance": 0.5291836256703958,
      "candidate_served_direction": [
        0.5751019806028272,
        -0.6328582699707993,
        0.5184092225609728
      ]
    },
    "wood_panelling": {
      "uv_rectangle": [
        0.23,
        0.5,
        0.287,
        0.645
      ],
      "mean_linear_luminance": 0.03985825776658887,
      "p95_linear_luminance": 0.06330302871920682,
      "candidate_served_direction": [
        0.5705515209814251,
        -0.23417723779770774,
        -0.7871670618129408
      ]
    }
  },
  "limits": [
    "LDR JPEG tone mapping and white balance are unknown; no lux, HDR or calibrated exposure claim.",
    "Panorama-to-E57 and Matterport-to-served rotations are diagnostic candidates, not accepted registrations.",
    "One distant key approximates distributed upper emitters; its shadows are presentation lighting.",
    "No floor receiver, source recoloring, global renderer exposure or Spark material change.",
    "The diffuse probe has no glossy environment reflections."
  ]
} as const;
