// Generated by tools/furniture-lighting/prepare_reflection_panorama.py.
export const GRAND_HALL_FURNITURE_REFLECTION_SOURCE = {
  "schema": "venviewer.furniture-reflection-hypothesis.v1",
  "authority": "presentation-experiment-only",
  "accepted_registration": false,
  "radiometrically_calibrated": false,
  "source": "sweep_041jpg.jpg",
  "source_sha256": "d9d056e2453a223144514bdca224bbdfb7e76f4bd7130008a3d811afa67eb974",
  "source_bytes": 6691673,
  "native_size": [
    8192,
    4096
  ],
  "derivative": "grand-hall-reflections-1024.jpg",
  "derivative_sha256": "941723fe24b5e24ce2afffa5736102f330688227ee441bb42199837320d2f742",
  "derivative_bytes": 178608,
  "derivative_size": [
    1024,
    512
  ],
  "candidate_served_from_panorama_rotation": [
    [
      0.5421045201181198,
      -0.010793654967898096,
      -0.8402417427621278
    ],
    [
      -0.011932688422580507,
      -0.9999155606673331,
      0.005146113324029152
    ],
    [
      -0.8402263386817347,
      0.007236611622030255,
      -0.5421875424958774
    ]
  ],
  "orientation": "Candidate rotation baked into pixels: Three r180 equirectUv atan(z,x)/(2pi)+0.5; image top is +Y. Scene environmentRotation is identity.",
  "processing": "RGB BOX downsample, inverse candidate rotation, wrapped bilinear resample, JPEG quality92 4:4:4. No exposure gain, inpainting or invented highlights.",
  "limitations": "8-bit tone-mapped JPEG, assumed sRGB; capture-time lighting and provisional azimuth. Native polar content retained. Not HDR, measured BRDF, accepted registration or current illumination."
} as const;
