// -----------------------------------------------------------------------------
// stage-manifest — the contract between a scene's authored material and the
// stage engine, the Lantern, the reaction layer and the audio engine.
//
// A scene's visual, sound and pokeable material is a parallel record keyed by
// scene index, so the instrument (craft-quiz-model.ts) and its tests never see
// it. Written by the assembling session on 2026-09-06 from Appendix A section 3
// of docs/superpowers/specs/2026-09-04-magnificent-quiz-design.md, under the
// owner's override of the same day: every asset is made digitally, so the
// provenance kinds gain "G" (generated by a named model from a recorded prompt)
// beside "Pr" (procedural, drawn by code). Nothing here may import from the
// instrument; a source-grep test holds that.
// -----------------------------------------------------------------------------
import { z } from "zod";

export const PROVENANCE_KINDS = ["P", "PD", "I", "F", "Pr", "C", "B", "G"] as const;

/** Every plane, cue and ink layer carries a card; the provenance gate fails the build without one. */
export const ProvenanceSchema = z.object({
  kind: z.enum(PROVENANCE_KINDS),
  /** The tool or model that made it: "code (WebGL2 fragment shader)", "ElevenLabs sound-generation v1", "Blender 4.2 Cycles". */
  tool: z.string().min(1),
  /** For kind "G": the exact prompt sent; for "Pr": the source file that draws it. */
  prompt: z.string().optional(),
  licence: z.string().min(1),
  url: z.string().optional(),
  fetchedOn: z.string().regex(/^\d{4}-\d{2}-\d{2}$/u),
  touchedBy: z.string().min(1),
});
export type Provenance = z.infer<typeof ProvenanceSchema>;

const IdSchema = z.string().regex(/^[a-z][a-z0-9-]*$/u);

export const PlaneKindSchema = z.enum(["lantern", "svg", "image"]);
export const PlaneSchema = z.object({
  id: IdSchema,
  kind: PlaneKindSchema,
  /** 0 = the farthest plane (least parallax), 1 = the nearest (7 px amplitude at 1). */
  depth: z.number().min(0).max(1),
  /** image: a URL under /trades-house-media/stage/; svg: a key in the scene's plane registry; lantern: the program id. */
  src: z.string().min(1),
  bytes: z.number().int().nonnegative(),
  provenance: ProvenanceSchema,
});
export type Plane = z.infer<typeof PlaneSchema>;

export const SPRING_PRESET_NAMES = ["gridSettle", "placementBounce", "camera", "heavy", "strike"] as const;
export const SpringPresetNameSchema = z.enum(SPRING_PRESET_NAMES);
export type SpringPresetName = z.infer<typeof SpringPresetNameSchema>;

/**
 * One row of a pokeable's rarity table. `at` is the poke count at which the
 * row fires, or a stated condition: "distinctProps:n" (n distinct props
 * touched in the scene) or "conditional:<id>" (a persisted fact). Rows are
 * deterministic by construction: identical for everyone, never random.
 */
export const StageRowSchema = z.object({
  at: z.union([
    z.number().int().positive(),
    z.string().regex(/^(distinctProps:\d+|conditional:[a-z][a-z0-9-]*)$/u),
  ]),
  spring: SpringPresetNameSchema,
  /** A cue id from the scene's audio.cues, or null for a silent stage. */
  cue: IdSchema.nullable(),
  /** Shown in the live region and, on the stage, beside the prop. In square brackets by convention. */
  caption: z.string().min(1).max(140),
  /** A line the Convener may speak after the reply; at most one per scene may carry one. */
  aside: z.string().max(240).optional(),
  reducedMotion: z.object({
    /** A CSS custom-property value the prop applies instead of moving (one colour step). */
    colorStep: z.string().min(1),
    caption: z.string().min(1).max(140),
  }),
});
export type StageRow = z.infer<typeof StageRowSchema>;

export const PERSIST_KEYS = ["initial", "chainSwing", "char", "potStruck", "sluiceLifted", "childSeen"] as const;

export const PropSchema = z.object({
  id: IdSchema,
  /** The accessible name of the button: what a layperson would call it, never a lexicon word of the scene's four worlds. */
  label: z.string().min(1).max(40),
  /** Percent of the stage: x/y the top-left corner, w/h the size. */
  box: z.object({
    x: z.number().min(0).max(100),
    y: z.number().min(0).max(100),
    w: z.number().min(0.5).max(100),
    h: z.number().min(0.5).max(100),
  }),
  states: z.array(StageRowSchema).min(1).max(6),
  /** Which run-persistent fact this prop sets (the persistence table in section 5). */
  persistKey: z.enum(PERSIST_KEYS).optional(),
});
export type Prop = z.infer<typeof PropSchema>;

export const BUS_NAMES = ["ambience", "music", "sfx", "ui"] as const;
export const BusNameSchema = z.enum(BUS_NAMES);
export type BusName = z.infer<typeof BusNameSchema>;

export const CueSchema = z.object({
  id: IdSchema,
  /** URL under /trades-house-media/stage/; one file per cue for now (the sprite belongs to a later card). */
  file: z.string().min(1),
  durationMs: z.number().int().positive(),
  /** The decoded length the encoder should have produced, for trimming encoder delay. Null until measured. */
  expectedSamples: z.number().int().positive().nullable(),
  gainDb: z.number().min(-40).max(6),
  bus: BusNameSchema,
  /** Every cue has a caption; the caption-parity test holds it. */
  caption: z.string().min(1).max(140),
  /** true for beds and any loop; loops play as two overlapping sources with an equal-power crossfade. */
  loop: z.boolean(),
  provenance: ProvenanceSchema,
});
export type Cue = z.infer<typeof CueSchema>;

/** The six shared bed elements, mixed per scene by gain (Appendix D). */
export const BedMixSchema = z.object({
  water: z.number().min(0).max(1),
  wind: z.number().min(0).max(1),
  fire: z.number().min(0).max(1),
  room: z.number().min(0).max(1),
  voices: z.number().min(0).max(1),
  night: z.number().min(0).max(1),
});
export type BedMix = z.infer<typeof BedMixSchema>;

export const OneShotSchema = z.object({
  cue: IdSchema,
  everyMsMin: z.number().int().positive(),
  everyMsMax: z.number().int().positive(),
});
export type OneShot = z.infer<typeof OneShotSchema>;

export const LANTERN_PROGRAMS = ["none", "river-gate", "fire", "frost", "ink-flood", "weather", "wax"] as const;
export const LanternProgramSchema = z.enum(LANTERN_PROGRAMS);
export type LanternProgramId = z.infer<typeof LanternProgramSchema>;

export const FRAME_GENRES = [
  "prospect-map", "ledger", "field-book", "register", "broadside", "almanac",
  "roup-roll", "section", "indenture", "ballad", "charter", "staircase",
] as const;
export const QUARTER_DAYS = [
  "lammas", "michaelmas", "hallowmas", "yule", "candlemas", "thaw", "beltane", "midsummer",
] as const;

export const MAX_LATCH_WORDS = 14;

export const SceneManifestSchema = z.object({
  /** 0 to 11 the twelve scenes; 12 the threshold. */
  sceneIndex: z.number().int().min(0).max(12),
  act: z.enum(["I", "II", "III"]),
  quarterDay: z.enum(QUARTER_DAYS),
  /** The one saturated practical in the frame. */
  hue: z.string().regex(/^#[0-9a-f]{6}$/u),
  frame: z.enum(FRAME_GENRES),
  planes: z.array(PlaneSchema).min(3).max(7),
  ink: z.object({
    planeId: IdSchema,
    segments: z.number().int().positive().max(3000),
    bytes: z.number().int().nonnegative(),
  }).nullable(),
  lantern: LanternProgramSchema,
  audio: z.object({
    cues: z.array(CueSchema),
    bed: BedMixSchema,
    oneShots: z.array(OneShotSchema),
  }),
  props: z.array(PropSchema).max(8),
  thursday: z.object({
    box: z.object({ x: z.number(), y: z.number(), w: z.number(), h: z.number() }),
    captionsByVisit: z.tuple([z.string(), z.string(), z.string()]),
  }).nullable(),
  /** The latch line: at most 14 words, names the next place or object, no question, no forecast of the reader. */
  latch: z.string().min(1).max(90),
});
export type SceneManifest = z.infer<typeof SceneManifestSchema>;

export function latchWordCount(latch: string): number {
  return latch.trim().split(/\s+/u).filter(Boolean).length;
}

/**
 * A light the tableau places for the Lantern's water to reflect: normalised
 * stage coordinates (0..1, y down), intensity 0..1, warmth 0 (moon-white) to
 * 1 (lantern amber). At most 16 per scene.
 */
export interface StageLight {
  readonly x: number;
  readonly y: number;
  readonly intensity: number;
  readonly warmth: number;
}
export const MAX_STAGE_LIGHTS = 16;
