// @omnitwin/types — Shared TypeScript interfaces, Zod schemas, and enums
//
// Modules below are grouped by runtime status:
//   LIVE    — actively consumed by @omnitwin/api and/or @omnitwin/web
//   ASPIRATIONAL — tested and exported, but not yet consumed at runtime;
//                  the web/API packages should import from here when the
//                  feature ships, rather than re-declaring types locally

export {
  VenueIdSchema,
  VenueSlugSchema,
  BrandColourSchema,
  TimezoneSchema,
  DEFAULT_VENUE_TIMEZONE,
  VenueSchema,
  CreateVenueSchema,
  type VenueId,
  type Timezone,
  type Venue,
  type CreateVenue,
} from "./venue.js";

export {
  SpaceIdSchema,
  SpaceSlugSchema,
  SpaceDimensionsSchema,
  FloorPlanPointSchema,
  FloorPlanOutlineSchema,
  SpaceSchema,
  CreateSpaceSchema,
  polygonBoundingBox,
  type SpaceId,
  type SpaceDimensions,
  type FloorPlanPoint,
  type PolygonBoundingBox,
  type Space,
  type CreateSpace,
  TRADES_HALL_GRAND_HALL_DIMENSIONS,
  TRADES_HALL_ROBERT_ADAM_ROOM_DIMENSIONS,
  TRADES_HALL_RECEPTION_ROOM_DIMENSIONS,
  TRADES_HALL_SALOON_DIMENSIONS,
  TRADES_HALL_ROOMS,
} from "./space.js";

export {
  ConfigurationIdSchema,
  ConfigurationStatusSchema,
  CONFIGURATION_STATUSES,
  LayoutStyleSchema,
  LAYOUT_STYLES,
  VISIBILITY_OPTIONS,
  VisibilitySchema,
  Vec3Schema,
  PlacedObjectIdSchema,
  AssetDefinitionIdSchema,
  PlacedObjectSchema,
  ConfigurationSchema,
  CreateConfigurationSchema,
  type ConfigurationId,
  type ConfigurationStatus,
  type LayoutStyle,
  type Visibility,
  type Vec3,
  type PlacedObjectId,
  type PlacedObject,
  type Configuration,
  type CreateConfiguration,
} from "./configuration.js";

// --- ASPIRATIONAL: template management not yet implemented in web/API ---
export {
  LayoutTemplateIdSchema,
  LayoutTemplateSchema,
  CreateLayoutTemplateSchema,
  type LayoutTemplateId,
  type LayoutTemplate,
  type CreateLayoutTemplate,
} from "./template.js";

export {
  FURNITURE_CATEGORIES,
  FurnitureCategorySchema,
  FurnitureDimensionsSchema,
  AssetDefinitionSchema,
  CreateAssetDefinitionSchema,
  type FurnitureCategory,
  type FurnitureDimensions,
  type AssetDefinition,
  type CreateAssetDefinition,
} from "./furniture.js";

// --- ASPIRATIONAL: unified scene-state store not yet consumed by web ---
export {
  VIEW_MODES,
  ViewModeSchema,
  CameraStateSchema,
  TRANSITION_STATES,
  TransitionStateSchema,
  SceneStateSchema,
  type ViewMode,
  type CameraState,
  type TransitionState,
  type SceneState,
} from "./scene.js";

// --- ASPIRATIONAL: runtime bundle manifest for T-091 real-venue loading ---
export {
  RUNTIME_VENUE_MANIFEST_V0_VERSION,
  RUNTIME_COORDINATE_SYSTEMS,
  RUNTIME_ASSET_ROLES,
  RUNTIME_ASSET_FORMATS,
  RUNTIME_LAYER_KINDS,
  IDENTITY_MATRIX4D,
  RuntimeManifestKeySchema,
  RuntimeAssetUriSchema,
  RuntimeSha256Schema,
  RuntimeCoordinateSystemSchema,
  RuntimeAssetRoleSchema,
  RuntimeAssetFormatSchema,
  RuntimeLayerKindSchema,
  RuntimeVec3Schema,
  Matrix4dSchema,
  RuntimeBoundsSchema,
  RuntimeAssetSchema,
  RuntimeGaussianSplatLayerSchema,
  RuntimeMeshLayerSchema,
  RuntimeRenderLayerSchema,
  RuntimeVenueManifestV0Schema,
  isRuntimeAssetUri,
  type RuntimeCoordinateSystem,
  type RuntimeAssetRole,
  type RuntimeAssetFormat,
  type RuntimeLayerKind,
  type RuntimeVec3,
  type Matrix4d,
  type RuntimeBounds,
  type RuntimeAsset,
  type RuntimeGaussianSplatLayer,
  type RuntimeMeshLayer,
  type RuntimeRenderLayer,
  type RuntimeVenueManifestV0Input,
  type RuntimeVenueManifestV0,
} from "./runtime-venue-manifest.js";

export {
  UserIdSchema,
  USER_ROLES,
  UserRoleSchema,
  EmailSchema,
  UserSchema,
  CreateUserSchema,
  type UserId,
  type UserRole,
  type User,
  type CreateUser,
} from "./user.js";

export {
  EnquiryIdSchema,
  ENQUIRY_STATUSES,
  EnquiryStatusSchema,
  VALID_ENQUIRY_TRANSITIONS,
  isValidEnquiryTransition,
  EnquirySchema,
  CreateEnquirySchema,
  GuestEnquirySchema,
  type EnquiryId,
  type EnquiryStatus,
  type Enquiry,
  type CreateEnquiry,
  type GuestEnquiry,
} from "./enquiry.js";

export {
  PricingRuleIdSchema,
  SUPPORTED_CURRENCIES,
  CurrencySchema,
  PRICING_TYPES,
  PricingTypeSchema,
  TierSchema,
  PricingRuleSchema,
  CreatePricingRuleSchema,
  PriceEstimateRequestSchema,
  PriceEstimateResponseSchema,
  LineItemSchema,
  ModifierSchema,
  type PricingRuleId,
  type Currency,
  type PricingType,
  type Tier,
  type PricingRule,
  type CreatePricingRule,
  type PriceEstimateRequest,
  type PriceEstimateResponse,
  type LineItem,
  type Modifier,
} from "./pricing.js";

export {
  SETUP_PHASES,
  SetupPhaseSchema,
  PHASE_METADATA,
  ImpliedAccessorySchema,
  ACCESSORY_RULES,
  accessoriesFor,
  defaultPhaseForCategory,
  type SetupPhase,
  type ImpliedAccessory,
} from "./hallkeeper-accessories.js";

export {
  ZONES,
  ZoneSchema,
  ManifestRowV2Schema,
  RowPositionSchema,
  PhaseZoneSchema,
  PhaseSchema,
  TimingSchema,
  SheetApprovalSchema,
  HallkeeperSheetV2Schema,
  type Zone,
  type ManifestRowV2,
  type RowPosition,
  type PhaseZone,
  type Phase,
  type Timing,
  type SheetApproval,
  type HallkeeperSheetV2,
} from "./hallkeeper-v2.js";

export {
  DayOfContactSchema,
  PhaseDeadlineSchema,
  EventInstructionsSchema,
  ConfigurationMetadataSchema,
  PlacedObjectMetadataSchema,
  emptyEventInstructions,
  hasInstructionContent,
  type DayOfContact,
  type PhaseDeadline,
  type EventInstructions,
  type ConfigurationMetadata,
  type PlacedObjectMetadata,
} from "./hallkeeper-instructions.js";

export {
  PhotoIdSchema,
  ALLOWED_PHOTO_CONTENT_TYPES,
  PhotoContentTypeSchema,
  LegacyPhotoSchema,
  LegacyPhotoUploadRequestSchema,
  LegacyPhotoUploadResponseSchema,
  ReferencePhotoSchema,
  type PhotoId,
  type PhotoContentType,
  type LegacyPhoto,
  type LegacyPhotoUploadRequest,
  type LegacyPhotoUploadResponse,
  type ReferencePhoto,
} from "./photo.js";

export {
  CANONICAL_ASSETS,
  getCanonicalAssetById,
  getCanonicalAssetBySlug,
  type CanonicalAsset,
  type TableShape,
} from "./asset-catalogue.js";

export {
  AccessibilityRequirementsSchema,
  DietarySummarySchema,
  DoorEventTypeSchema,
  DoorEventSchema,
  DoorScheduleEntrySchema,
  DoorScheduleSchema,
  EquipmentTagSchema,
  EQUIPMENT_TAGS,
  DOOR_EVENT_TYPES,
  emptyAccessibilityRequirements,
  hasAccessibilityContent,
  hasCriticalAccessibility,
  emptyDietarySummary,
  dietaryTotal,
  hasDietaryContent,
  emptyDoorSchedule,
  hasDoorScheduleContent,
  type AccessibilityRequirements,
  type DietarySummary,
  type DoorEventType,
  type DoorEvent,
  type DoorScheduleEntry,
  type DoorSchedule,
  type EquipmentTag,
} from "./event-requirements.js";

export {
  CONFIGURATION_REVIEW_STATUSES,
  ConfigurationReviewStatusSchema,
  VALID_CONFIGURATION_REVIEW_TRANSITIONS,
  isValidConfigurationReviewTransition,
  isTerminalReviewStatus,
  isPlannerEditable,
  ReviewHistoryEntryIdSchema,
  ReviewHistoryEntrySchema,
  type ConfigurationReviewStatus,
  type ReviewHistoryEntryId,
  type ReviewHistoryEntry,
} from "./configuration-review.js";

export {
  ConfigurationSheetSnapshotIdSchema,
  ConfigurationSheetSnapshotSchema,
  isSnapshotApproved,
  type ConfigurationSheetSnapshotId,
  type ConfigurationSheetSnapshot,
} from "./configuration-sheet-snapshot.js";

export {
  BRAND,
  INK,
  DARK,
  SEVERITY_PALETTE,
  SHEET_TYPE,
  SHEET_SPACING,
  type SeverityPaletteEntry,
  type TypeStep,
} from "./design-tokens.js";

export {
  buildAccessibilityCallouts,
  buildDoorScheduleSummary,
  severityRank,
  type AccessibilityCallout,
  type AccessibilityCalloutSeverity,
  type DoorScheduleSummary,
  type DoorScheduleSummaryEntry,
  type DoorScheduleSummaryEvent,
} from "./event-sheet-rendering.js";

// --- ASPIRATIONAL: solver not yet consumed by web/API at runtime ---
export {
  solveLayout,
  SolverInputSchema,
  SolverOutputSchema,
  SolverConfigSchema,
  ComplianceReportSchema,
  FireExitSchema,
  DEFAULT_SOLVER_CONFIG,
  SOLVER_ASSETS,
  SOLVER_ASSET_DIMENSIONS,
  type SolverInput,
  type SolverOutput,
  type SolverConfig,
  type ComplianceReport,
  type FireExit,
  pointInPolygon,
  distanceToEdge,
  distanceToPoint,
  circleInPolygon,
  rectInPolygon,
  lineIntersectsRect,
  generateGridPoints,
  checkAisleWidths,
  checkFireExitClearance,
  checkMaxTravelDistance,
  generateComplianceReport,
  solveDinnerRounds,
  solveTheatre,
  solveBoardroom,
  solveCabaret,
  solveCocktail,
  solveCeremony,
  solveDinnerBanquet,
} from "./solver/index.js";

export {
  UsernameSchema,
  NewUsernameSchema,
  LayoutSlugSchema,
  ShortCodeSchema,
  RESERVED_USERNAMES,
  SHORTCODE_ALPHABET_CHARS,
  SHORTCODE_LENGTH,
  buildLayoutPathKey,
  slugifyLayoutName,
  LayoutResolveResponseSchema,
  LayoutResolveQuerySchema,
  type Username,
  type LayoutSlug,
  type ShortCode,
  type LayoutAliasKind,
  type LayoutResolveResponse,
  type LayoutResolveQuery,
} from "./url-identifiers.js";
