import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// The self-hosted fonts must be Google Fonts' own files and rules, not a
// look-alike: text is meant to render from the same bytes it did when the
// pages linked fonts.googleapis.com. provenance.json records what
// scripts/self-host-google-fonts.mjs fetched; these checks hold the committed
// files to it.
// ---------------------------------------------------------------------------

interface Provenance {
  readonly stylesheets: Readonly<Record<string, {
    readonly source: string;
    readonly css: Readonly<Record<string, { readonly file: string; readonly faces: number; readonly googleResponseSha256: string }>>;
  }>>;
  readonly licences: Readonly<Record<string, { readonly file: string; readonly source: string; readonly sha256: string }>>;
  readonly files: Readonly<Record<string, { readonly source: string; readonly bytes: number; readonly sha256: string }>>;
}

const fontsDirectory = join(import.meta.dirname, "..", "styles", "fonts");
const provenance = JSON.parse(readFileSync(join(fontsDirectory, "provenance.json"), "utf8")) as Provenance;
const sha256 = (bytes: Buffer | string): string => createHash("sha256").update(bytes).digest("hex");
const FACE = /\/\* [\w-]+ \*\/\n@font-face \{\n[^}]*\}\n/gu;
const LOCAL_SOURCE = /url\(\.\/files\/([^)]+)\)/gu;

function stylesheet(file: string): { readonly header: string; readonly body: string } {
  const text = readFileSync(join(fontsDirectory, file), "utf8");
  const newline = text.indexOf("\n");
  return { header: text.slice(0, newline), body: text.slice(newline + 1) };
}

function withGoogleSources(css: string): string {
  return css.replace(LOCAL_SOURCE, (_match, name: string) => {
    const file = provenance.files[name];
    if (file === undefined) throw new Error(`${name} has no provenance.`);
    return `url(${file.source})`;
  });
}

const allStylesheets = Object.values(provenance.stylesheets).flatMap((group) => Object.values(group.css));

describe("self-hosted Google Fonts", () => {
  it("serves every face from the file Google served, byte for byte", () => {
    const names = Object.keys(provenance.files);
    expect(names.length).toBeGreaterThanOrEqual(60);
    for (const name of names) {
      const record = provenance.files[name];
      if (record === undefined) continue;
      const bytes = readFileSync(join(fontsDirectory, "files", name));
      expect(record.source, name).toMatch(/^https:\/\/fonts\.gstatic\.com\//u);
      expect(bytes.length, name).toBe(record.bytes);
      expect(sha256(bytes), name).toBe(record.sha256);
      expect(bytes.subarray(0, 4).toString("latin1"), name).toBe(name.endsWith(".woff2") ? "wOF2" : "wOFF");
    }
  });

  it("keeps exactly the files its stylesheets name", () => {
    const referenced = new Set(allStylesheets.flatMap(({ file }) =>
      [...stylesheet(file).body.matchAll(LOCAL_SOURCE)].map((match) => match[1] ?? "")));
    const onDisk = readdirSync(join(fontsDirectory, "files")).sort();
    expect([...referenced].sort()).toEqual(onDisk);
    expect(Object.keys(provenance.files).sort()).toEqual(onDisk);
  });

  it("reproduces Google's @font-face rules exactly for the default build", () => {
    for (const [group, { css }] of Object.entries(provenance.stylesheets)) {
      const build = css["default"];
      if (build === undefined) throw new Error(`${group} has no default build.`);
      const { header, body } = stylesheet(build.file);
      expect(header, build.file).toMatch(/^\/\* Generated by scripts\/self-host-google-fonts\.mjs /u);
      // Swapping the local names back for Google's URLs must give back the
      // stylesheet Google returned, character for character.
      expect(sha256(withGoogleSources(body)), build.file).toBe(build.googleResponseSha256);
      expect(body.match(FACE)?.length, build.file).toBe(build.faces);
      for (const face of body.match(FACE) ?? []) expect(face, build.file).toContain("font-display: swap;");
    }
  });

  it("only overrides faces the default build declares, with the same descriptors", () => {
    for (const [group, { css }] of Object.entries(provenance.stylesheets)) {
      const defaults = css["default"];
      if (defaults === undefined) throw new Error(`${group} has no default build.`);
      const withoutSource = (face: string): string => face.replace(/^ {2}src: .*$/mu, "");
      const defaultFaces = new Set((stylesheet(defaults.file).body.match(FACE) ?? []).map(withoutSource));
      for (const [build, { file, faces }] of Object.entries(css)) {
        if (build === "default") continue;
        const overrides = stylesheet(file).body.match(FACE) ?? [];
        expect(overrides.length, file).toBe(faces);
        expect(overrides.length, file).toBeGreaterThan(0);
        for (const face of overrides) expect(defaultFaces.has(withoutSource(face)), `${file}: ${face}`).toBe(true);
      }
    }
  });

  it("ships the licence of every family it serves", () => {
    const families = new Set(allStylesheets.flatMap(({ file }) =>
      [...stylesheet(file).body.matchAll(/font-family: '([^']+)';/gu)].map((match) => match[1] ?? "")));
    expect([...families].sort()).toEqual(Object.keys(provenance.licences).sort());
    for (const [family, licence] of Object.entries(provenance.licences)) {
      const bytes = readFileSync(join(fontsDirectory, licence.file));
      expect(sha256(bytes), family).toBe(licence.sha256);
      expect(bytes.toString("utf8"), family).toContain("SIL OPEN FONT LICENSE Version 1.1");
    }
  });
});
