/**
 * Build-owned local HD worker dependency-plan input.
 *
 * This is deliberately data only. Runtime callers and the browser cannot
 * replace it. The strict Foundry manifest compiler binds the canonical digest
 * before the value reaches the local workbench.
 */
export const LOCAL_HD_WORKER_GENERATED_MANIFEST_PAYLOAD: unknown = {
  schemaVersion: "omnitwin.foundry.local-hd-worker-manifest.v0",
  manifestId: "omnitwin-local-hd-worker-candidate-2026-07-19",
  reviewedOn: "2026-07-19",
  reviewClass: "engineering_screen_only",
  overall: "planned_not_installed_not_execution_ready",
  manifestState: "recorded_with_open_closure_items",
  installationState: "not_installed",
  runtimeVerificationState: "not_performed",
  binding: "not_bound_to_current_source_or_plan",
  execution: "disabled",
  authority: "none",
  architecture: {
    localWindows: {
      status: "planned_components_only",
      gaussianTraining: "not_enabled",
    },
    gpuWorker: {
      status: "separate_review_required",
      canonicalForGaussianTraining: true,
      workerImage: "not_defined",
    },
  },
  activity: {
    workerInstallationPerformed: false,
    workerRuntimeVerificationPerformed: false,
    venueDataAccessed: false,
    cloudWorkloadStarted: false,
    modelOptimizationStarted: false,
  },
  capabilityLanes: [
    {
      id: "e57_read_only_intake",
      label: "Read-only E57 intake",
      runtimeProfile: "Independent Windows x64 CPython 3.10 candidate profile",
      componentIds: ["pye57", "libe57format", "xerces-c"],
      executionLocation: "local_windows_candidate",
      state: "planned_closure_incomplete_execution_disabled",
      boundary: "The existing probe is not wired to this screen and its dependency bytes are not yet bound. No E57 worker is ready.",
    },
    {
      id: "geometry_registration_and_qa",
      label: "Geometry registration and QA",
      runtimeProfile: "Independent Open3D Windows x64 CPython 3.10 candidate profile",
      componentIds: ["open3d"],
      executionLocation: "local_windows_candidate",
      state: "planned_closure_incomplete_execution_disabled",
      boundary: "Only the Open3D root wheel is pinned. Its Python and compiled third-party closure is still open; optional ML, model, dataset, and CUDA content is excluded.",
    },
    {
      id: "camera_registration",
      label: "Camera registration",
      runtimeProfile: "Independent COLMAP no-CUDA binary plus weight-free hloc source profile",
      componentIds: ["colmap", "hloc"],
      executionLocation: "local_windows_candidate",
      state: "planned_closure_incomplete_execution_disabled",
      boundary: "The initial hloc allow-list is SIFT, nearest-neighbour matching, exhaustive pairs, and pycolmap only. No learned model or automatic download is allowed.",
    },
    {
      id: "gaussian_training",
      label: "Gaussian training",
      runtimeProfile: "Separate reviewed Python 3.10, PyTorch, CUDA GPU-worker profile",
      componentIds: ["gsplat"],
      executionLocation: "reviewed_remote_gpu_worker_only",
      state: "execution_disabled_under_current_architecture",
      boundary: "Execution is disabled under the current architecture. Local Windows Gaussian training is not enabled; a new immutable reviewed GPU-worker image is required.",
    },
    {
      id: "photometric_compensation",
      label: "Photometric compensation",
      runtimeProfile: "Separate reviewed PPISP GPU-worker candidate profile",
      componentIds: ["ppisp"],
      executionLocation: "reviewed_remote_gpu_worker_only",
      state: "planned_closure_incomplete_execution_disabled",
      boundary: "PPISP remains an optional separate derivative step. Its runtime dependencies and attributions are not closed and its optional dataset is excluded.",
    },
  ],
  components: [
    {
      id: "pye57",
      label: "pye57",
      role: "Read-only E57 Python wrapper candidate",
      version: "0.4.19",
      tag: "v0.4.19",
      revision: "64c9000738ad54242e87e1da6bca6b683b13374b",
      repository: "https://github.com/davidcaron/pye57",
      artifact: {
        kind: "pypi_wheel",
        url: "https://files.pythonhosted.org/packages/51/9c/95f355e5a2f3fe5654d3d518831b91aa0c6943f66690750e9ac3f7fe3d9d/pye57-0.4.19-cp310-cp310-win_amd64.whl",
        byteSize: 1128676,
        sha256: "b0fdc023d88706739ff5bfa22022bd69611b2394298d477a9cc91c669c4cbcf8",
        digestEvidence: "publisher_attested_and_observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "MIT",
      legalTexts: [
        {
          kind: "license",
          label: "pye57 MIT licence",
          url: "https://raw.githubusercontent.com/davidcaron/pye57/64c9000738ad54242e87e1da6bca6b683b13374b/LICENSE",
          byteSize: 1050,
          sha256: "7e4eba8170c2d4e56bba2c744c9ead1861fabda3ff54ecc13c44d9df1c6732c6",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "missing_from_selected_binary",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Pin an exact CPython 3.10 Windows x64 interpreter artifact and hash.",
        "Pin NumPy, pyquaternion, and every transitive artifact, licence, and notice.",
        "Package the libE57Format, CRC++, and Xerces legal texts omitted from the selected wheel.",
        "Reconcile this CPython 3.10 wheel profile with the current Python 3.13 local-probe evidence before enabling it.",
      ],
      excludedAssets: [
        "Source E57 files, embedded images, point records, and venue data are not dependency assets and were not accessed for this manifest.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "libe57format",
      label: "libE57Format",
      role: "Native E57 core pinned by pye57 0.4.19",
      version: "3.1.1",
      tag: "v3.1.1",
      revision: "1914b8ea972251d3bb49a33828497dde683205d9",
      repository: "https://github.com/asmaloney/libE57Format",
      artifact: {
        kind: "github_tag_archive",
        url: "https://github.com/asmaloney/libE57Format/archive/refs/tags/v3.1.1.tar.gz",
        byteSize: 207108,
        sha256: "949e73db3cb90ed7d286c49d12c6925813ead8d92ff9b84e0fba17fa015194d0",
        digestEvidence: "observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "BSL-1.0 AND MIT AND BSD-3-Clause",
      legalTexts: [
        {
          kind: "license",
          label: "libE57Format Boost Software License 1.0",
          url: "https://raw.githubusercontent.com/asmaloney/libE57Format/1914b8ea972251d3bb49a33828497dde683205d9/LICENSE.md",
          byteSize: 1338,
          sha256: "c9bff75738922193e67fa726fa225535870d2aa1059f91452c411736284ad566",
          redistributionRequired: true,
        },
        {
          kind: "license",
          label: "libE57Format auxiliary MIT licence",
          url: "https://raw.githubusercontent.com/asmaloney/libE57Format/1914b8ea972251d3bb49a33828497dde683205d9/LICENSE-MIT.md",
          byteSize: 1101,
          sha256: "8ce9ce1a2d14d0a5ddccb915017e9e0e2a4d5c12b5559d227ecdd3342ab94fa9",
          redistributionRequired: true,
        },
        {
          kind: "license",
          label: "Bundled CRC++ BSD-3-Clause licence",
          url: "https://raw.githubusercontent.com/asmaloney/libE57Format/1914b8ea972251d3bb49a33828497dde683205d9/extern/CRCpp/LICENSE",
          byteSize: 1480,
          sha256: "954e7c6730168114b296fbcc60532fa7ce64236e1adf17c147878bb7949be09e",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "open_dependency_notice_review",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Reverify the observed GitHub tag archive against the immutable commit on every acquisition.",
        "Pin the Windows compiler, build flags, runtime libraries, and complete native dependency tree.",
        "Bind the exact native files incorporated into the eventual pye57 runtime bundle.",
      ],
      excludedAssets: [
        "Repository fixtures and example E57 files are excluded from the worker bundle.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "xerces-c",
      label: "Apache Xerces-C++",
      role: "XML dependency selected by the pye57 0.4.19 Windows build",
      version: "3.2.3",
      tag: "v3.2.3",
      revision: "cf1912ac95d4147be08aef4e78f894a3919277d9",
      repository: "https://github.com/apache/xerces-c",
      artifact: {
        kind: "source_archive",
        url: "https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.2.3.tar.gz",
        byteSize: 7120270,
        sha256: "fb96fc49b1fb892d1e64e53a6ada8accf6f0e6d30ce0937956ec68d39bd72c7e",
        digestEvidence: "publisher_attested_and_observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "Apache-2.0",
      legalTexts: [
        {
          kind: "license",
          label: "Apache Xerces-C++ licence",
          url: "https://raw.githubusercontent.com/apache/xerces-c/cf1912ac95d4147be08aef4e78f894a3919277d9/LICENSE",
          byteSize: 11358,
          sha256: "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30",
          redistributionRequired: true,
        },
        {
          kind: "notice",
          label: "Apache Xerces-C++ NOTICE",
          url: "https://raw.githubusercontent.com/apache/xerces-c/cf1912ac95d4147be08aef4e78f894a3919277d9/NOTICE",
          byteSize: 560,
          sha256: "95e5cca2ff3d0801841d9d17f0eec16bfb02dd6893ff7e55da4ec5a5dd30aa52",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "missing_from_selected_binary",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Bind the exact compiler and runtime provenance of the xerces-c_3_2.dll bundled by pye57.",
        "Package both the Apache licence and NOTICE beside any redistributed DLL.",
      ],
      excludedAssets: [
        "Xerces samples, tests, and documentation payloads are excluded from the minimal runtime bundle.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "open3d",
      label: "Open3D",
      role: "Local geometry registration, ICP, TSDF, and QA candidate",
      version: "0.19.0",
      tag: "v0.19.0",
      revision: "1e7b17438687a0b0c1e5a7187321ac7044afe275",
      repository: "https://github.com/isl-org/Open3D",
      artifact: {
        kind: "pypi_wheel",
        url: "https://files.pythonhosted.org/packages/bc/1c/0219416429f88ebc94fcb269fb186b153affe5b91dffe8f9062330d7776d/open3d-0.19.0-cp310-cp310-win_amd64.whl",
        byteSize: 69150378,
        sha256: "18bb8b86e5fa9e582ed11b9651ff6e4a782e6778c9b8bfc344fc866dc8b5f49c",
        digestEvidence: "publisher_attested_and_observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "MIT",
      legalTexts: [
        {
          kind: "license",
          label: "Open3D MIT licence",
          url: "https://raw.githubusercontent.com/isl-org/Open3D/1e7b17438687a0b0c1e5a7187321ac7044afe275/LICENSE",
          byteSize: 1139,
          sha256: "e5439bd70250da5f17b3435ff9efb05e96e7f9fdc34248d3355b0026baadaa41",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "open_dependency_notice_review",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Pin the complete Python dependency set for the selected CPython profile.",
        "Inventory every compiled third-party library and package all required legal notices.",
        "Define and verify a CPU-only capability surface before any local execution is enabled.",
      ],
      excludedAssets: [
        "Optional machine-learning models, datasets, CUDA components, example media, and downloaded assets are excluded.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "colmap",
      label: "COLMAP",
      role: "No-CUDA structure-from-motion and global-mapper candidate",
      version: "4.1.1",
      tag: "4.1.1",
      revision: "a0d785fba74b2664f31edc4a29026a8b27c00f67",
      repository: "https://github.com/colmap/colmap",
      artifact: {
        kind: "github_release_asset",
        url: "https://github.com/colmap/colmap/releases/download/4.1.1/colmap-x64-windows-nocuda.zip",
        byteSize: 120217143,
        sha256: "faf1247d2ec90933aa8bd003709790abf0211cdc132cceec4c831718f2e0895a",
        digestEvidence: "publisher_attested_and_observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "BSD-3-Clause",
      legalTexts: [
        {
          kind: "license",
          label: "COLMAP COPYING",
          url: "https://raw.githubusercontent.com/colmap/colmap/a0d785fba74b2664f31edc4a29026a8b27c00f67/COPYING.txt",
          byteSize: 1909,
          sha256: "ab30dabb4f0a6731f980108f57aa160cc8f5cebae6984e01a5d109df99669233",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "missing_from_selected_binary",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "The selected 278-entry binary archive contains no licence, notice, copying, attribution, copyright, or third-party file.",
        "Generate and review a complete notice pack for every bundled DLL before redistribution.",
        "Enforce SIFT extraction plus SIFT brute-force matching and disable every model or cache network download.",
        "Verify the exact no-CUDA command surface and its interaction with the separately pinned hloc profile.",
      ],
      excludedAssets: [
        "The CUDA release asset, ALIKED N16/N32, SIFT-LightGlue, ALIKED-LightGlue, learned ONNX paths, default vocabulary-tree URLs, external datasets, example images, and all model or database content are excluded.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "hloc",
      label: "Hierarchical-Localization",
      role: "Weight-free camera-registration orchestration candidate",
      version: "1.4",
      tag: "v1.4",
      revision: "80ccb7ee3bc048cb3a8ef221c5bc4d8ac25d5792",
      repository: "https://github.com/cvg/Hierarchical-Localization",
      artifact: {
        kind: "github_tag_archive",
        url: "https://github.com/cvg/Hierarchical-Localization/archive/refs/tags/v1.4.tar.gz",
        byteSize: 10488989,
        sha256: "78bc0d0377f5f0bc949ac1811ff6f2c102a25e858d02de6cdcbed808f4c3ce33",
        digestEvidence: "observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "Apache-2.0",
      legalTexts: [
        {
          kind: "license",
          label: "Hierarchical-Localization Apache licence",
          url: "https://raw.githubusercontent.com/cvg/Hierarchical-Localization/80ccb7ee3bc048cb3a8ef221c5bc4d8ac25d5792/LICENSE",
          byteSize: 11357,
          sha256: "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "open_dependency_notice_review",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Pin the exact SIFT, nearest-neighbour, exhaustive-pairs, pycolmap, and transitive Python dependency artifacts.",
        "Enforce the weight-free allow-list and block every automatic network download.",
        "Reverify the observed GitHub tag archive against the immutable commit on every acquisition.",
      ],
      excludedAssets: [
        "All learned extractors, matchers, retrieval configurations, submodules, checkpoints, model-zoo downloads, and datasets are excluded.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "gsplat",
      label: "gsplat",
      role: "Gaussian training implementation candidate for a separately reviewed GPU worker",
      version: "1.5.3",
      tag: "v1.5.3",
      revision: "937e29912570c372bed6747a5c9bf85fed877bae",
      repository: "https://github.com/nerfstudio-project/gsplat",
      artifact: {
        kind: "github_tag_archive",
        url: "https://github.com/nerfstudio-project/gsplat/archive/refs/tags/v1.5.3.tar.gz",
        byteSize: 27454693,
        sha256: "8a24428b8ea2ce7c3e10fcf5aa20e20fe503b8329c96db797f4eab703729aac3",
        digestEvidence: "observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "Apache-2.0",
      legalTexts: [
        {
          kind: "license",
          label: "gsplat Apache licence",
          url: "https://raw.githubusercontent.com/nerfstudio-project/gsplat/937e29912570c372bed6747a5c9bf85fed877bae/LICENSE",
          byteSize: 11345,
          sha256: "96a4f89293c0df19880da9b0e35f67589f5885ea61b224ef16bb2bd599a8a44d",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "open_dependency_notice_review",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Pin the exact Python, PyTorch 2.4, CUDA 12.4, ninja, NumPy, jaxtyping, rich, and transitive worker closure.",
        "Create an immutable GPU-worker image digest, software bill of materials, and complete notice pack.",
        "Qualify owned or authorised inputs and trained-output rights independently of the code licence.",
      ],
      excludedAssets: [
        "All external checkpoints, example datasets, downloaded media, and unlisted research methods are excluded.",
        "Local Windows Gaussian training is excluded under the current architecture.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
    {
      id: "ppisp",
      label: "PPISP",
      role: "Optional photometric-compensation candidate kept separate from captured truth",
      version: "1.2.1",
      tag: "v1.2.1",
      revision: "df33809f7b3b20ac06de088dfc871b144b8fb54d",
      repository: "https://github.com/nv-tlabs/ppisp",
      artifact: {
        kind: "github_tag_archive",
        url: "https://github.com/nv-tlabs/ppisp/archive/refs/tags/v1.2.1.tar.gz",
        byteSize: 59388,
        sha256: "6024ede41eed932ed9caaf48d4dcf2d8b14f0c44f14c1cc47de0d266dea22d6c",
        digestEvidence: "observed",
        reverifyOnAcquire: true,
      },
      licenseSpdx: "Apache-2.0",
      legalTexts: [
        {
          kind: "license",
          label: "PPISP Apache licence",
          url: "https://raw.githubusercontent.com/nv-tlabs/ppisp/df33809f7b3b20ac06de088dfc871b144b8fb54d/LICENSE",
          byteSize: 10785,
          sha256: "595bbb9155ab35e0ff891f89c022eec23782cbaed84dc68297afa06df2d7bd4a",
          redistributionRequired: true,
        },
        {
          kind: "attribution",
          label: "PPISP third-party attributions",
          url: "https://raw.githubusercontent.com/nv-tlabs/ppisp/df33809f7b3b20ac06de088dfc871b144b8fb54d/ATTRIBUTIONS.md",
          byteSize: 13977,
          sha256: "2d37462260349fbcc3d679f04478e00c17f83dee8ab6fcd668326d785e2478de",
          redistributionRequired: true,
        },
      ],
      noticeClosureStatus: "open_dependency_notice_review",
      closureStatus: "root_identity_pinned_dependency_closure_open",
      closureItems: [
        "Pin every Python and GPU dependency artifact and reconcile the full attribution set.",
        "Define a separate derivative-output contract that never replaces captured or metric truth.",
        "Reverify the observed GitHub tag archive against the immutable commit on every acquisition.",
      ],
      excludedAssets: [
        "The optional PhysicalAI-NuRec-PPISP dataset, all source imagery, and any unlisted model or checkpoint are excluded.",
      ],
      installationState: "not_installed",
      runtimeVerificationState: "not_performed",
      execution: "disabled",
    },
  ],
  exclusions: [
    {
      id: "pdal-deferred",
      label: "PDAL deferred from this narrower closure",
      reason: "The broader T-534 preferred path mentions PDAL 2.10.2, but its exact Windows artifact, dependency tree, licence notices, and runtime profile are not closed in this manifest.",
    },
    {
      id: "raw-xgrids-formats",
      label: "Raw XGRIDS formats and SDKs",
      reason: "XBIN, LCC, and LCC2 decoding, reverse engineering, and SDK bundling remain excluded. Only official rights-cleared SOG, SPZ, PLY, GLB, or other documented exports may enter ordinary intake.",
    },
    {
      id: "legacy-moving-main-spz",
      label: "Moving-main SPZ acquisition",
      reason: "The legacy image installs SPZ from a moving default branch. It is not part of this immutable candidate path.",
    },
    {
      id: "legacy-moving-main-dn-splatter",
      label: "Moving-main DN-Splatter acquisition",
      reason: "The legacy image shallow-clones DN-Splatter from a moving default branch. Its optional models, datasets, and dependency closure are not approved.",
    },
    {
      id: "unlisted-models-and-datasets",
      label: "Unlisted models, checkpoints, and datasets",
      reason: "No automatic model-zoo, dataset, example-media, or checkpoint download is included. Every future model or dataset needs an exact separate identity and rights review.",
    },
    {
      id: "ai-captured-truth-substitution",
      label: "AI substitution for captured truth",
      reason: "Any later AI enhancement remains a separately labelled derivative. It cannot replace captured geometry, captured appearance, measurement evidence, or provenance records.",
    },
  ],
  legacyDocker: {
    path: "infra/runpod/Dockerfile",
    disposition: "do_not_build_run_or_deploy",
    reason: "It contains stale pye57 and Open3D pins, an unversioned COLMAP package, moving-main SPZ and DN-Splatter acquisitions, and no immutable whole-image dependency or notice closure.",
  },
  nextAction: "Finish the local E57, Open3D, COLMAP, and weight-free hloc dependency and notice closure; separately define and review the RunPod-canonical gsplat and PPISP GPU-worker closure. Do not build the legacy RunPod image or touch venue data.",
};
